# Combine Daily Temperature CSV Parts

This notebook joins the three raw daily temperature CSV parts from `data/raw/` into one pandas DataFrame, filters out non-depot cities, and writes the depot-only dataset to `data/processed/daily-temperature-for-depots.csv`.

In [1]:
from pathlib import Path

import pandas as pd

PROJECT_DIR = Path.cwd()
RAW_DIR = PROJECT_DIR / "data" / "raw"
PROCESSED_DIR = PROJECT_DIR / "data" / "processed"
PROCESSED_DIR.mkdir(exist_ok=True)

pd.set_option("display.max_columns", 50)

In [2]:
csv_files = [
    RAW_DIR / "daily-temperature-for-30-sites-to-2022-part1.csv",
    RAW_DIR / "daily-temperature-for-30-sites-to-2022-part2.csv",
    RAW_DIR / "daily-temperature-for-30-sites-to-2022-part3.csv",
]

In [3]:
parts = [pd.read_csv(file) for file in csv_files]
df = pd.concat(parts, ignore_index=True)

print(f"Combined rows: {len(df):,}")
print(f"Combined columns: {df.shape[1]:,}")
df.head()

Combined rows: 2,138,037
Combined columns: 6

                  site        date statistic  temperature       lat        lon
0  Auckland (Auckland)  01/01/1966   Maximum         22.2 -37.00813  174.78873
1  Auckland (Auckland)  01/01/1966   Minimum         13.9 -37.00813  174.78873
2  Auckland (Auckland)  01/01/1966   Average         18.0 -37.00813  174.78873
3  Auckland (Auckland)  02/01/1966   Maximum         23.9 -37.00813  174.78873
4  Auckland (Auckland)  02/01/1966   Minimum         17.1 -37.00813  174.78873

In [4]:
df['site'].unique()

<StringArray>
[            'Auckland (Auckland)',          'Blenheim (Marlborough)',
       'Christchurch (Canterbury)', 'Dannevirke (Manawatū-Whanganui)',
                 'Dunedin (Otago)',             'Gisborne (Gisborne)',
                'Gore (Southland)',              'Hamilton (Waikato)',
           'Hokitika (West Coast)',        'Invercargill (Southland)',
            'Kerikeri (Northland)',        'Lake Tekapo (Canterbury)',
          'Masterton (Wellington)',       'Milford Sound (Southland)',
            'Napier (Hawke's Bay)',                 'Nelson (Nelson)',
         'New Plymouth (Taranaki)',              'Queenstown (Otago)',
            'Reefton (West Coast)',         'Rotorua (Bay of Plenty)',
         'Tara Hills (Canterbury)', 'Taumarunui (Manawatū-Whanganui)',
                 'Taupō (Waikato)',        'Tauranga (Bay of Plenty)',
             'Timaru (Canterbury)',    'Waiouru (Manawatū-Whanganui)',
         'Wellington (Wellington)',  'Whanganui (Manawatū-Whanganui)',
         'Whangaparāoa (Auckland)',           'Whangārei (Northland)']
Length: 30, dtype: str

In [5]:
sites_to_keep = ['Whangārei (Northland)','Auckland (Auckland)','Hamilton (Waikato)','Tauranga (Bay of Plenty)',"Napier (Hawke's Bay)",'New Plymouth (Taranaki)','Dannevirke (Manawatū-Whanganui)','Wellington (Wellington)','Blenheim (Marlborough)','Christchurch (Canterbury)','Queenstown (Otago)','Dunedin (Otago)']

filtered = df[df['site'].isin(sites_to_keep)]

filtered

,site,date,statistic,temperature,lat,lon
0,Auckland (Auckland),01/01/1966,Maximum,22.2,-37.00813,174.78873
1,Auckland (Auckland),01/01/1966,Minimum,13.9,-37.00813,174.78873
2,Auckland (Auckland),01/01/1966,Average,18.0,-37.00813,174.78873
3,Auckland (Auckland),02/01/1966,Maximum,23.9,-37.00813,174.78873
4,Auckland (Auckland),02/01/1966,Minimum,17.1,-37.00813,174.78873
...,...,...,...,...,...,...
2138032,Whangārei (Northland),2022-12-30,Minimum,16.6,-35.76900,174.36400
2138033,Whangārei (Northland),2022-12-30,Average,21.3,-35.76900,174.36400
2138034,Whangārei (Northland),2022-12-31,Maximum,24.4,-35.76900,174.36400
2138035,Whangārei (Northland),2022-12-31,Minimum,15.4,-35.76900,174.36400
2138036,Whangārei (Northland),2022-12-31,Average,19.9,-35.76900,174.36400

In [6]:
mapping = {'Whangārei (Northland)': 'Whangarei','Auckland (Auckland)': 'Auckland','Hamilton (Waikato)': 'Hamilton','Tauranga (Bay of Plenty)': 'Tauranga',"Napier (Hawke's Bay)": 'Napier','New Plymouth (Taranaki)': 'New Plymouth','Dannevirke (Manawatū-Whanganui)': 'Palmerston North','Wellington (Wellington)':'Wellington','Blenheim (Marlborough)':'Blenheim','Christchurch (Canterbury)':'Christchurch','Queenstown (Otago)':'Queenstown','Dunedin (Otago)':'Dunedin'}

filtered['site'] = filtered['site'].map(mapping)

filtered

              site        date statistic  temperature       lat        lon
0         Auckland  01/01/1966   Maximum         22.2 -37.00813  174.78873
1         Auckland  01/01/1966   Minimum         13.9 -37.00813  174.78873
2         Auckland  01/01/1966   Average         18.0 -37.00813  174.78873
3         Auckland  02/01/1966   Maximum         23.9 -37.00813  174.78873
4         Auckland  02/01/1966   Minimum         17.1 -37.00813  174.78873
...            ...         ...       ...          ...       ...        ...
2138032  Whangarei  2022-12-30   Minimum         16.6 -35.76900  174.36400
2138033  Whangarei  2022-12-30   Average         21.3 -35.76900  174.36400
2138034  Whangarei  2022-12-31   Maximum         24.4 -35.76900  174.36400
2138035  Whangarei  2022-12-31   Minimum         15.4 -35.76900  174.36400
2138036  Whangarei  2022-12-31   Average         19.9 -35.76900  174.36400

[895969 rows x 6 columns]

In [7]:
filtered.info()
filtered.tail()

<class 'pandas.DataFrame'>
Index: 895969 entries, 0 to 2138036
Data columns (total 6 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   site         895969 non-null  str
 1   date         895969 non-null  str
 2   statistic    895969 non-null  str
 3   temperature  895969 non-null  float64
 4   lat          895969 non-null  float64
 5   lon          895969 non-null  float64
dtypes: float64(3), str(3)
memory usage: 47.8 MB

              site        date statistic  temperature     lat      lon
2138032  Whangarei  2022-12-30   Minimum         16.6 -35.769  174.364
2138033  Whangarei  2022-12-30   Average         21.3 -35.769  174.364
2138034  Whangarei  2022-12-31   Maximum         24.4 -35.769  174.364
2138035  Whangarei  2022-12-31   Minimum         15.4 -35.769  174.364
2138036  Whangarei  2022-12-31   Average         19.9 -35.769  174.364

In [8]:
output_path = PROCESSED_DIR / "daily-temperature-for-depots.csv"
filtered.to_csv(output_path, index=False)

print(f"Saved combined CSV to: {output_path.resolve()}")

Saved combined CSV to: /Users/aaronho/Documents/code/projects-2/supply-chain-solutions/warehouse-heat-intelligence/data/processed/daily-temperature-for-depots.csv